### ISSUE TITLE
how to generate results_coco.csv?

### ISSUE THREAD

**Issue by raven0327** [roeiherz/CanonicalSg2Im#1]
hi roeiherz,
i recently run your train program (scene graph to layout), i just wanna get the data_frame(results_coco.csv) like you did. could you please release the code, it is for academic purposes only.
thanks a lot.
Tian ruiwen

**Comment by roeiherz** [comment]
Thanks for the comment!

I add the _layout_generation.py_ script to generate the data frame. I also fixed the README accordingly. Try to run  _layout_generation.py_; it should work.

**Comment by raven0327** [comment]
thanks a lot !
