### ISSUE TITLE
a problem in base_dataset.py

### ISSUE THREAD

**Issue by raven0327** [roeiherz/CanonicalSg2Im#2]
from sg2im/data/base_dataset.py
ln89: def add_learnt_triplets(self, triplets, O):
                triplets = np.unique(triplets, axis=0).astype('int')
                new_triplets = []
                N_REL = len(self.vocab['pred_name_to_idx'].values())
                conv_counts = np.zeros((N_REL, N_REL + 1))
                triplets = np.array(triplets)
i couldn't understand the meaning of variable 'O' , thanks for answering my question.

**Comment by roeiherz** [comment]
Hi,

Thanks for your comment! 

It seems we used this variable in the past to represents the number of objects. However, it is not used in the method anymore, and thus you can ignore it.
