### ISSUE TITLE
I can't find the "vocab.json" in VG download page

### ISSUE THREAD

**Issue by YanJohn** [roeiherz/CanonicalSg2Im#5]
how to get this json document?

**Comment by roeiherz** [comment]
We downloaded the vocab from other repositories, but I also attached
[vocab.zip](https://github.com/roeiherz/CanonicalSg2Im/files/5924196/vocab.zip)

 it here.

**Comment by roeiherz** [comment]
We downloaded the vocab by the given instructions, but I also attached the file below.
[vocab.zip](https://github.com/roeiherz/CanonicalSg2Im/files/5924202/vocab.zip)

**Comment by YanJohn** [comment]
Danke
